# Generated by Django 5.0.9 on 2026-09-17 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sprint_task_task_unique_task_number_per_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.task')),
            ],
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'depends_on'), name='unique_task_dependency_edge'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(check=models.Q(('task', models.F('depends_on')), _negated=True), name='task_cannot_depend_on_itself'),
        ),
    ]
