# Generated by Django 5.0.9 on 2026-09-17 17:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_taskdependency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='core.member')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='core.sprint')),
            ],
        ),
        migrations.CreateModel(
            name='SprintCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_hours_at_start', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='core.sprint')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('remaining_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='core.task')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='capacity',
            constraint=models.UniqueConstraint(fields=('member', 'sprint'), name='unique_capacity_per_member_sprint'),
        ),
        migrations.AddConstraint(
            model_name='sprintcommitment',
            constraint=models.UniqueConstraint(fields=('sprint', 'task'), name='unique_commitment_per_sprint_task'),
        ),
        migrations.AddConstraint(
            model_name='worklog',
            constraint=models.UniqueConstraint(fields=('task', 'date'), name='unique_worklog_per_task_day'),
        ),
    ]
