# Generated by Django 5.0.9 on 2026-09-17 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('sprints', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintcommitment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='timeoff',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off', to='projects.member'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='capacity',
            constraint=models.UniqueConstraint(fields=('member', 'sprint'), name='unique_capacity_per_member_sprint'),
        ),
        migrations.AddConstraint(
            model_name='sprintcommitment',
            constraint=models.UniqueConstraint(fields=('sprint', 'task'), name='unique_commitment_per_sprint_task'),
        ),
        migrations.AddConstraint(
            model_name='worklog',
            constraint=models.UniqueConstraint(fields=('task', 'date'), name='unique_worklog_per_task_day'),
        ),
    ]
